### ISSUE TITLE
A bug in data/davis2016_data_utils.py

### ISSUE THREAD

**Issue by dzy1997** [antonilo/unsupervised_detection#3]
line 263-266 is:

```
first_fname_numbers.append(np.arange(N, N + len(fnames) - t_len,
                                    dtype=np.int32))
last_fname_numbers.append(np.arange(N + len(fnames) - t_len, N + len(fnames),
                                    dtype=np.int32))
```

the second line should be

```
last_fname_numbers.append(np.arange(N + t_len, N + len(fnames),
                                    dtype=np.int32))
```

Otherwise first_fname_numbers and last_fname_numbers will not have the same number of elements

**Comment by antonilo** [comment]
hi @dzy1997, thanks for your report. Actually, this is not a bug. In the test_inputs, you don't need the first_fname_numbers and last_fname_numbers to have the same number of elements. The reason is that you can only select a single time difference between frames at testing time.
If `t_len>0`, then last_fname_numbers should be should contain all the frames for which the time difference is not defined (because it will go out of the video). This frames are the one in `np.arange(N + len(fnames) - t_len, N + len(fnames)`, for which `t_len` needs to be necessarily negative.
Feel free to comment if you need more explanations!

**Comment by dzy1997** [comment]
hi @antonilo , I read the code context again and I think I get what you mean. Just to make sure my understanding is correct, by setting direction as 1 for first_fname_numbers and -1 for last_fname_numbers, you are calculating optical flow forward for most of the frames, but backward for the last few frames of a video, so that you can generate masks for every frame in the video.
For example, I have 10 frames in a video and t_len=2, I calculate forward flow for frame 1-8 and backward flow for frame 9 and 10. Am I correct?

**Comment by antonilo** [comment]
yes this is correct!
